### PR TITLE
Quote Python version numbers

### PR DESCRIPTION
**Pull request by jugmac00**
... as with 3.10 this would break anyway.

### CODE REVIEW

**Review by mgedmin — COMMENTED** [review]
Seems a bit inconsistent to do it here but not in the matrix.include bits.

**Comment by mgedmin** [comment]
I've released check-python-versions 0.16.1 that will preserve these quotes if you use --add/--drop to update the list of supported version numbers and .travis.yml had all the version numbers quoted.

(check-python-versions was already adding quotes around the special case of "3.10", so it wouldn't be treated as a float.)

**Comment by icemac** [comment]
For me this only adds visual noise.
Why do you think it would break on 3.10? `3.9-dev` also works without quotes.

**Comment by jugmac00** [comment]
`3.9-dev` is a string, `3.10` is a float

**Comment by mauritsvanrees** [comment]
I have not tried what happens, but I can imagine that this will get fixed in tox and/or Travis.
Just a guess.

**Comment by mgedmin** [comment]
This issue has nothing to do with tox.

While Travis could hardcode a special-case for converting Python 3.1 to 3.10 (assuming nobody will ever want the actual Python 3.1), somehow I don't think they will do that.

The right thing to do is to specify Python 3.10 as `"3.10"` in YAML files.

I'm ambivalent on whether we want to quote all other Python versions.  Pros:
- these versions are not floats and we shouldn't be using float syntax
- when people come in to add 3.10 they will be gently directed to follow the example of existing quoted versions and they will avoid a mistake
- consistency

Cons:
- visual noise
- it's not really necessary before 3.10 final is released and supported by Travis (which takes like a month after the upstream release)

**Comment by dataflake** [comment]
My vote would be for consistency, even if it adds visual noise.

**Review by icemac — APPROVED** [review]
Okay, convinced.

**Pull request merged**
