### PR TITLE
Add documentation for readthedocs support.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by dataflake** [comment]
You were too quick, I just added a further clarification that explains what I was stumbling over, namely which flag governs the creation on the RTD configuration

**Comment by dataflake** [comment]
Oops, this isn't merged yet, I misread the mentioned PR note above.

Please take a look at my addition, I believe this is how it works, correct?

**Comment by icemac** [comment]
> Please take a look at my addition, I believe this is how it works, correct?

Yes, that's the way it works.

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
