### PR TITLE
Drop support of Python 3.7

### PR DESCRIPTION
**Pull request by loechel**
Remove Python 3.7 from list of supported Python Versions, as of today (2023-10-07) Python 3.7 is already end of Life (since 2023-06-27). See https://devguide.python.org/versions/ for reference.

See also #200.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]
I am fine with merging this PR because all it does is change the `drop-legacy-python` script. I don't know anyone who uses that script after Python 2 support has been removed...

**Review by icemac — CHANGES_REQUESTED** [review]
This script has to be adapted to be useable to actually drop Python 3.7 support. It was already used on all zopefoundation packages to drop Python 2.7 to 3.6 support, so this part is no longer needed and the change log messages should not mention it any more.

But really dropping Python 3.7 support also means to adapt all the templates and remove 3.7 from tox.ini, the c code build scripts etc.

**Comment by icemac** [comment]
Maybe the script should be reworked into one adding support for new version (aka 3.12) + the already existing dropping of outdated versions.

**Comment by tseaver** [comment]
If for nothing else than a tiny contribution to reducing our carbon footprint, can we please quit doing CI on EOL Python versions as a matter of policy?  Under current rules, that would give us five "stable" Python versions to test, plus the one in alpha/beta for the succeeding release.

**Comment by dataflake** [comment]
I think the time has come to rework the templates in order to get rid of Python 3.7. I'm going to extend this PR soon.

**Review by d-maurer — APPROVED** [review]

**Review by tseaver — APPROVED** [review]

**Comment by dataflake** [comment]
@icemac I have removed references to the `drop-legacy-python.py` script from the Readme.

**Comment by icemac** [comment]
> @icemac I have removed references to the `drop-legacy-python.py` script from the Readme.

@dataflake Do you envision to no longer to use `drop-legacy-python.py` or should it become part of the ususal update config run?

**Comment by dataflake** [comment]
I don't use that script, for me the only use would be as a scripting example.

**Pull request merged**
