### PR TITLE
Unify pure-python templates

### PR DESCRIPTION
**Pull request by icemac**
This is done by adding a `--with-pypy` switch on the command line.
`.meta.cfg` stores whether PyPy is supported or not.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM

**Comment by mgedmin** [comment]
(It would be nice if we could use Jinja2 instead of %-formatting, but not now.)

**Comment by icemac** [comment]
> (It would be nice if we could use Jinja2 instead of %-formatting, but not now.)

This could be an idea. %-formatting was the only one within Python which does not interfere with the format inside the templates thus did not require any additional quoting.

**Comment by icemac** [comment]
Thank you for looking into this PR. 😀

**Pull request merged**
