### PR TITLE
Use tomlkit for TOML read/write operations

### PR DESCRIPTION
**Pull request by dataflake**
This PR is an alternative to #209. It does two things:

- replace `toml` use with `tomlkit`
- update dependencies in `requirements.txt` to the latest versions that still support Python 3.7

Running this code against current Zope yields the following diff in `.meta.toml`:

```diff
diff --git a/.meta.toml b/.meta.toml
index 82f0c085f..07cac2b24 100644
--- a/.meta.toml
+++ b/.meta.toml
@@ -2,7 +2,7 @@
 # https://github.com/zopefoundation/meta/tree/master/config/zope-product
 [meta]
 template = "zope-product"
-commit-id = "571024f0"
+commit-id = "babc889c"

 [python]
 with-pypy = false
@@ -11,6 +11,7 @@ with-sphinx-doctests = false
 with-windows = true
 with-macos = true
 with-future-python = true
+with-appveyor = false

 [coverage]
 fail-under = 80
```

The different is most likely due to the change in the `_set_python_config_value` method where I always use the default `False` because some values were `None` at that point, which `tomlkit` didn't like.

### CODE REVIEW

**Comment by dataflake** [comment]
Instead of changing the behavior of `_set_python_config_value` I have decided to fix the real reason: Several script arguments that want to store true or false had an inconsistent default of `None`. I have corrected those. The outcome is still the same as the diff shown above.

**Comment by sallner** [comment]
We can also do it this way, but it actually does not use the capabilities of `tomlkit` to add and preserve comments now. It does the same as before, so I am fine from this perspective.

**Review by sallner — COMMENTED** [review]
It looks okay, to me, although we might end up with all default values in the `meta.toml` now.

**Comment by dataflake** [comment]
> It looks okay to me, although we might end up with all default values in the `meta.toml` now.

I was thinking about that and to be honest I don't think that's a bad thing. It's very explicit.

**Review by icemac — APPROVED** [review]
Finally I got to this PR.

**Comment by icemac** [comment]
Thank you for this PR. 😃

**Pull request merged**
