### PR TITLE
Allow `setuptools <= 75.6.0`.

### PR DESCRIPTION
**Pull request by icemac**
`zc.buildout` is nowadays tested against this version. Maybe we addidtionally need a final release of `zc.buildout` as support for these newer versions is only in `4.0.0a1`.

### CODE REVIEW

**Comment by icemac** [comment]
See also https://github.com/buildout/buildout/issues/673

**Comment by icemac** [comment]
Hm, that `setuptools` version does not support Python 3.8 anymore. So I'd also suggest starting to drop support for that Python version. (I'd like to do this in a sepate PR.)

**Comment by icemac** [comment]
> Hm, that `setuptools` version does not support Python 3.8 anymore. So I'd also suggest starting to drop support for that Python version. (I'd like to do this in a sepate PR.)

See https://github.com/zopefoundation/meta/pull/293

**Comment by dataflake** [comment]
> `zc.buildout` is nowadays tested against this version. Maybe we addidtionally need a final release of `zc.buildout` as support for these newer versions is only in `4.0.0a1`.

I think it's fine. https://github.com/buildout/buildout/pull/671 didn't make any code changes to zc.buildout so it should work with the current release.

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
