### PR TITLE
Allow to add additional sources for isort.

### PR DESCRIPTION
**Pull request by icemac**
This PR is needed for https://github.com/zopefoundation/RestrictedPython/pull/234.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]
I know why this is needed but I still hate the fact that we now have this one package where the tests are in a different place and use a different testing framework.

**Comment by icemac** [comment]
Using `pytest` was an experiment because RestrictedPython 4.0 was a complete rewrite, so we wanted to use the newest tools. The result makes RestrictedPython different form the other packages but at least running the tests via `tox` is the same.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Comment by dataflake** [comment]
Pleas do not forget that any package that uses different tooling or different layout rules represents a high maintenance burden and automatically discourages the usual contributors to help out because all of a sudden they need to learn new tools, just for one package. It's a mistake to change one package's policies just to use the "newest tools".

**Pull request merged**
